spring:
  cloud:
    gateway:
      routes:
        - id: microservicio-productos
          uri: lb://microservicio-productos
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2
            - name: Ejemplo
              args:
                mensaje: Hola mi mensaje personalizado
                cookieNombre: usuario
                cookieValor: RobertoCamaron
        - id: microservicio-items
          uri: lb://microservicio-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2