spring:
  cloud:
    gateway:
      routes:
        - id: microservicio-productos
          uri: lb://microservicio-productos
          predicates:
            - Path=/api/productos/**
            - Header= token, \d+
            - Header= Content-Type,application/json
            - Method=GET, POST
            - Query=color, verde
            - Cookie=color, azul
          filters:
            - StripPrefix=2
            - EjemploCookie=Hola mi mensaje personalizado, usuario, RobertoCamaron
        - id: microservicio-items
          uri: lb://microservicio-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=nombre, roberto