resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
    instances:
      items:
        baseConfig: defecto
  timelimiter:
    configs:
      defecto:
        timeoutDuration: 2s
    instances:
      items:
        baseConfig: defecto